### PR TITLE
Vt02

### PR DESCRIPTION
**Pull request by vijayaprasad**
Added lineitem

### CODE REVIEW

**Comment by pcopus** [comment]
Vijay, is there someone on the client subteam that can review this? I'm noticing we have two pull requests open on client sprint_2, we should try to clear them if they're ready to go...

**Comment by srawani** [comment]
vijay please assign someone to view your code .

**Comment by kasarlashushruth** [comment]
I already reviewed and added comment what to change, @vijayaprasad  please do it then later someone will review.

@srawani why to someone you can review it too.
Thank you

**Comment by pcopus** [comment]
Vijay, do you have more changes to commit here, or should we cancel the pull request, or what? Anything going into sprint 2 needs to go in tonight.

**Comment by sxs71620** [comment]
These changes are already merged with my commit

**Pull request closed without merging**
